### ISSUE TITLE
cant have more admins

### ISSUE THREAD

**Issue by s-balint** [CHR15cs/CS2-Practice-Plugin#40] opened 2024-01-05 01:29 UTC
Hi

For some reason I cant set more then 1 admins for the plugin.
I tried a lot of options, but It just doesnt work. If I set myself for admin it works, but as soon as I add another admin, even I lose my admin permissions.

This is my current admins.json
{
  "x": {
    "identity": "76561198269522581",
    "immunity": 100,
    "flags": [
      "@css/root",
      "@CSPracc/admin"
    ],
    "groups": [
      "#css/admin"
    ],
    "command_overrides": {
      "css_plugins": true,
      "css": false
    }
  },

  "y": {
    "identity": "76561198190149171",
    "immunity": 100,
    "flags": [
     "@CSPracc/admin"
    ],
    "groups": [
      "#css/admin"
    ],
    "command_overrides": {
      "css_plugins": true,
      "css": false
    }
  }
}

**Comment by CHR15cs** [comment] 2024-01-05 14:26
also what does css_admins_list print for you?

**Comment by s-balint** [comment] 2024-01-05 14:42
I was using the latest version.

**Comment by CHR15cs** [comment] 2024-01-05 15:44
Seems to be an issue in the admin manager.
I testet it using your admins.json file.
I could not execute any admin command until I saw the STEAM USERID validated message
[Allies Chat][CHR15 (119008051)]: .pracc  **<-----  Did not work**
SV:  "CHR15<3><[U:1:119008051]><>" STEAM USERID validated
[Allies Chat][CHR15 (119008051)]: .pracc **<---- did work**

I will try to reach out to the person who implemented the admin manager and see what could be the problem

**Comment by CHR15cs** [comment] 2024-01-06 15:13
Seems like it actually is just delayed until some sort of connection with the steam servers is established.
I will add a functionality to disable admin requirement

**Comment by CHR15cs** [comment] 2024-01-09 18:07
closing since its confirmed that its a valve issue.
Next release will contain a functionality to disable admin requirement

**Closed by CHR15cs** 2024-01-09 18:07 UTC
